/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account': RouteRecordInfo<'/account', '/account', Record<never, never>, Record<never, never>>,
    '/demo': RouteRecordInfo<'/demo', '/demo', Record<never, never>, Record<never, never>>,
    '/kitchen': RouteRecordInfo<'/kitchen', '/kitchen', Record<never, never>, Record<never, never>>,
    '/kitchen/': RouteRecordInfo<'/kitchen/', '/kitchen', Record<never, never>, Record<never, never>>,
    '/kitchen/add': RouteRecordInfo<'/kitchen/add', '/kitchen/add', Record<never, never>, Record<never, never>>,
    '/kitchen/make': RouteRecordInfo<'/kitchen/make', '/kitchen/make', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/make': RouteRecordInfo<'/make', '/make', Record<never, never>, Record<never, never>>,
    '/soups/[name]': RouteRecordInfo<'/soups/[name]', '/soups/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
  }
}
